services:
  nginx:
    container_name: 'nginx'
    image: 'nginx:1.24'
    environment:
      REMOTE_ORIGIN: '${REMOTE_ORIGIN:-http://stable-media-r2.freefeed.net}'
    ports:
      - '${HTTP_PORT:-8080}:80'
    volumes:
      - './nginx-templates:/etc/nginx/templates'
      - './webroot:/usr/share/nginx/html'
  imgproxy:
    container_name: 'imgproxy'
    image: 'darthsim/imgproxy:v3'
    expose:
      - "8080"
    environment:
      IMGPROXY_USE_ETAG: 'true'
      IMGPROXY_MAX_SRC_RESOLUTION: 40
      IMGPROXY_JPEG_PROGRESSIVE: 'true'
